In [1]:
import nest_asyncio
nest_asyncio.apply()
import twint
import pandas as pd

In [2]:
c = twint.Config()

c.Search = "#GoodByeJokowi"
c.Limit = 200
c.Since = "2022-01-06"
c.Until = "2022-04-06"
c.Lang = "id"
c.Hide_output = True
c.Debug = True
c.Pandas = True

In [3]:
%%time
try:
    print("Mulai Crawling")
    
    # konversi output ke format dataframe
    def twint_to_dataframe(columns):
        return twint.output.panda.Tweets_df[columns]
    
    # Mulai crawling
    twint.run.Search(c)
     
    # Save data crawling
    data = twint_to_dataframe(['date', 'username', 'tweet'])
    
    
except Exception as e:
    print(e)
print("Selesai")
print("=======")

Mulai Crawling
Selesai
=======
Wall time: 1min 26s

In [23]:
data

,date,username,tweet
0,2022-04-06 06:59:54,masaan64,@The_BosGenk Ada apa ni ko ada taggar #GoodBy...
1,2022-04-06 06:59:27,RBugeh,"@The_BosGenk sssst,, #GoodByeJokowi #GoodByeJ..."
2,2022-04-06 06:58:56,OmegaF1998,@Android_AK_47 Jangan biarkan Mahasiswa Berger...
3,2022-04-06 06:56:40,Aki_jupi,"@akunkelima212 Two period it's been so long, I..."
4,2022-04-06 06:56:37,mhbmuhib17,"Di era Jokowi NASAKOM dihidupkan kembali, Isla..."
...,...,...,...
199,2022-04-06 05:14:34,JakTar9,"President gagal Listrik naik, solar langka, m..."
200,2022-04-06 05:14:31,Hartati44247904,"@PanciBozz Suka üòäüëç,,,ikutan ya #GoodbyeJokowi..."
201,2022-04-06 05:14:28,PopoleTv,@emprosay #GoodByeJokowi
202,2022-04-06 05:14:19,SaskiOktavia,@N1n9_471KU #GoodByeJokowi #GoodByeJokowi
203,2022-04-06 05:13:27,HermanBudiSant4,"@UtangJpu Mohon maaf,kita dulu ber ikrar Tritu..."

In [25]:
data = data['tweet']
data

0      @The_BosGenk Ada apa ni ko ada taggar  #GoodBy...
1      @The_BosGenk sssst,, #GoodByeJokowi  #GoodByeJ...
2      @Android_AK_47 Jangan biarkan Mahasiswa Berger...
3      @akunkelima212 Two period it's been so long, I...
4      Di era Jokowi NASAKOM dihidupkan kembali, Isla...
                             ...
199    President gagal  Listrik naik, solar langka, m...
200    @PanciBozz Suka üòäüëç,,,ikutan ya  #GoodbyeJokowi...
201                             @emprosay #GoodByeJokowi
202           @N1n9_471KU #GoodByeJokowi  #GoodByeJokowi
203    @UtangJpu Mohon maaf,kita dulu ber ikrar Tritu...
Name: tweet, Length: 204, dtype: object

In [26]:
# Save data
data.to_csv('dataset_fix.csv', index=False)

In [27]:
df = pd.read_csv('dataset_fix.csv')
df

                                                 tweet
0    @The_BosGenk Ada apa ni ko ada taggar  #GoodBy...
1    @The_BosGenk sssst,, #GoodByeJokowi  #GoodByeJ...
2    @Android_AK_47 Jangan biarkan Mahasiswa Berger...
3    @akunkelima212 Two period it's been so long, I...
4    Di era Jokowi NASAKOM dihidupkan kembali, Isla...
..                                                 ...
199  President gagal  Listrik naik, solar langka, m...
200  @PanciBozz Suka üòäüëç,,,ikutan ya  #GoodbyeJokowi...
201                           @emprosay #GoodByeJokowi
202         @N1n9_471KU #GoodByeJokowi  #GoodByeJokowi
203  @UtangJpu Mohon maaf,kita dulu ber ikrar Tritu...

[204 rows x 1 columns]